# Generated by Django 4.2.13 on 2024-06-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0002_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('test_comments', models.TextField(max_length=2000, verbose_name='Текс комментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myblog.post', verbose_name='публикация')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
