# Generated by Django 4.2.13 on 2024-06-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='test_comments',
            new_name='text_comments',
        ),
    ]
