# Generated by Django 4.2.13 on 2024-06-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0004_rename_test_comments_comments_text_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myblog.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text_comments',
            field=models.TextField(max_length=2000, verbose_name='Текст комментария'),
        ),
    ]
